version: '3.8'

networks:
  wpnet:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jealefev/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jealefev/data/wordpress

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    networks:
      - wpnet

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - wpnet

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wpnet
